In [2]:
import os

In [5]:
directory_contents = os.listdir()

print(directory_contents)
for item in directory_contents:
    if os.path.isdir(item):
        print(item)

['.ipynb_checkpoints', 'cifarffcommands.txt', 'cifar_launch.py', 'COMPheuristic-per_column', 'COMPheuristic-per_column-greedy', 'COMPheuristic-per_column-Thompson-0.7', 'COMPheuristic-per_column-Thompson0.5', 'COMPheuristic-per_column-UCB-0.7', 'COMPheuristic-per_column.pdf', 'COMPheuristic2-3-layers-per_column-stuck0.5', 'COMPheuristic2-3-layers-per_column-Thompson0.5', 'data', 'data.py', 'data_dir', 'draft.ipynb', 'exp_dir', 'fc-mnist.ps1', 'launch.ps1', 'layers.py', 'mnistexperiments', 'mnistexperiments010', 'mnistexperiments2', 'mnistexperiments5', 'mnistexperimentsOneLayerSuperSup', 'mnistexperimentsOneLayerSuperSup.pdf', 'mnistffcommands.ps1', 'mnist_all_curves_full.pdf', 'mnist_all_curves_full101.pdf', 'mnist_all_curves_full5.pdf', 'mnist_launch.py', 'models.py', 'plot_cifar.py', 'plot_mnist.py', 'random-per_column', 'random-per_column.pdf', 'README_ff.md', 'README_rnn.md', 'rnn-baseline.ps1', 'rnn-supersub.ps1', 'rnn_mnist_launch.py', 'rnn_models.py', 'rnn_plottingscripts.py', 

In [15]:
folders = set([folder[:-4] for folder in os.listdir() if os.path.isdir(folder)])

In [14]:
set(folders)

{'',
 '.ipynb_checkpo',
 'COMPheuristic-per_co',
 'COMPheuristic-per_column-Thompso',
 'COMPheuristic-per_column-Thompson',
 'COMPheuristic-per_column-UCB',
 'COMPheuristic-per_column-gr',
 'COMPheuristic2-3-layers-per_column-Thompso',
 'COMPheuristic2-3-layers-per_column-stuc',
 '__pycac',
 'data',
 'exp',
 'mnistexperim',
 'mnistexperime',
 'mnistexperiment',
 'mnistexperimentsOneLayerSupe',
 'random-per_co',
 'stuck-heur-rand--2-3-layers-per_column-Thompso'}

In [7]:
import torch
from torch import nn

torch.manual_seed(3)
linear = nn.Linear(5, 2)
linearbis = nn.Linear(2, 5)

torch.manual_seed(3)
linear2 = nn.Linear(5, 2)
linearbis2 = nn.Linear(2, 5)

In [8]:
linear.weight

Parameter containing:
tensor([[-0.4434, -0.3528, -0.1915, -0.4231, -0.0254],
        [-0.3934,  0.2432,  0.2180,  0.0845,  0.3469]], requires_grad=True)

In [9]:
linear2.weight

Parameter containing:
tensor([[-0.4434, -0.3528, -0.1915, -0.4231, -0.0254],
        [-0.3934,  0.2432,  0.2180,  0.0845,  0.3469]], requires_grad=True)

In [11]:
linearbis.weight 

Parameter containing:
tensor([[-0.4952, -0.1393],
        [-0.6305, -0.0574],
        [-0.4588,  0.6352],
        [ 0.4912,  0.5301],
        [ 0.2097, -0.4034]], requires_grad=True)

In [13]:
linearbis2.weight


Parameter containing:
tensor([[-0.4952, -0.1393],
        [-0.6305, -0.0574],
        [-0.4588,  0.6352],
        [ 0.4912,  0.5301],
        [ 0.2097, -0.4034]], requires_grad=True)