In [1]:
import torch

In [7]:
import torch
from torch import nn

torch.manual_seed(3)
linear = nn.Linear(5, 2)
linearbis = nn.Linear(2, 5)

torch.manual_seed(3)
linear2 = nn.Linear(5, 2)
linearbis2 = nn.Linear(2, 5)

In [8]:
linear.weight

Parameter containing:
tensor([[-0.4434, -0.3528, -0.1915, -0.4231, -0.0254],
        [-0.3934,  0.2432,  0.2180,  0.0845,  0.3469]], requires_grad=True)

In [9]:
linear2.weight

Parameter containing:
tensor([[-0.4434, -0.3528, -0.1915, -0.4231, -0.0254],
        [-0.3934,  0.2432,  0.2180,  0.0845,  0.3469]], requires_grad=True)

In [11]:
linearbis.weight 

Parameter containing:
tensor([[-0.4952, -0.1393],
        [-0.6305, -0.0574],
        [-0.4588,  0.6352],
        [ 0.4912,  0.5301],
        [ 0.2097, -0.4034]], requires_grad=True)

In [13]:
linearbis2.weight


Parameter containing:
tensor([[-0.4952, -0.1393],
        [-0.6305, -0.0574],
        [-0.4588,  0.6352],
        [ 0.4912,  0.5301],
        [ 0.2097, -0.4034]], requires_grad=True)